name: Report An Issue
description: "Report a bug you've found"
title: "[Bug]: "
labels: "bug"
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug! If you need real-time help, join us on Discord.
      
- type: input
  id: description
  attributes:
    label: Describe the bug
    description: "Provide a clear and concise description of what the bug is"
    placeholder: "Example - Bot fails to respond to '!command' in Discord chat"
  validations:
    required: true

- type: input
  id: expected-behaviour
  attributes:
    label: What behaviour did you expect?
    description: "Provide a clear and concise description of what you expected to happen"
    placeholder: "Example - Bot should respond to '!command' with a message"
  validations:
    required: true

- type: input
  id: reproduce-steps
  attributes:
    label: Steps to reproduce the bug
    description: "Provide us clear steps to reproduce the bug"
    placeholder: "Example - Open xyz channel and run !command"
  validations:
    required: true

- type: dropdown
  id: frequency
  attributes:
    label: How frequent do you see this bug?
    options:
      - Everytime (Very Frequently)
      - Less Frequently
      - Rarely
  validations:
    required: true

- type: dropdown
  id: priority
  attributes:
    label: What is the priority of this issue?      
    options:
    - Needs to be addressed immediately
    - Needs to be addressed quickly
    - Needs to be addressed on a reasonable timescale
    - Should be addressed when able
    - Should be addressed eventually

- type: textarea
  id: additional-context
  attributes:
    label: Add any other context about the problem here
  validations:
    required: true

