name: Release

on:
  workflow_dispatch:
    

jobs:
  release:
    permissions:
        contents: write
        issues: write
        pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
        with:
          node-version: 20

      - run: npx semantic-release
        env:
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
